- name: add terminator debian repository
  apt_repository: repo='ppa:gnome-terminator'

- name: add sublime debian repository
  apt_repository: repo='ppa:webupd8team/sublime-text-3'

- name: update apt cache
  apt: update_cache=yes

- name: install common dependencies
  apt: pkg={{item}} state=installed
  with_items:
    - tig
    - vim
    - ack-grep
    - terminator
    - sublime-text-installer