- name: download docker compose binary
  shell: curl -L https://github.com/docker/compose/releases/download/1.5.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

- name: set docker compose binary permission
  file: path=/usr/local/bin/docker-compose mode="u=rwx,g=xr,o=xr"